services:
 sim:
  image: python:3.10-buster
  ports:
  - 5000:5000
  volumes:
  - ./backend:/backend
  working_dir: /backend
  command: sh -c "pip install -r requirements.txt && python main.py"

  
 front:
  image: node:14-buster
  ports:
  - 80:8080
  environment:
  - xd:xd
  
  volumes:
  - ./frontend:/frontend
  working_dir: /frontend
  command: sh -c "npm i && npm run dev"



volumes:
  frontend:
  backend: